/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "DefaultChestNames"

pluginManagement {
    repositories {
        gradlePluginPortal()
        maven("https://papermc.io/repo/repository/maven-public/")
    }
}