name: DefaultChestNames
main: com.taamc.DefaultChestNames.DefaultChestNames
version: ${version}
api-version: 1.16
author: ryan_the_leach
authors: [ryan_the_leach]
website: 
thread: 
softdepend:
description: 
commands:
permissions:

